### ISSUE TITLE
Algoritme schrijven/zoeken dat nog niet bezochte locaties opzoekt

### ISSUE THREAD

**Issue by ndsmyter** [ndsmyter/Robotica#3]
We zouden nog een algoritme moeten hebben, dat gegeven een kaart (met de bezochte punten enzo op) uitzoekt welke posities het best nog eens zou bezoeken.

Zo hebben we bijvoorbeeld bij de cirkel-figuur dat de robot niet naar het midden gaat maar hele tijd rondjes blijft draaien. Het zou beter zijn dat de robot stopt als het nog eens op hetzelfde pad is (dat is een ander probleem) en dan bekijkt welke punten het nog niet bezocht heeft. Als het dan zou kunnen doorhebben dat het naar het midden van de cirkel eens zou moeten rijden zou dat al een hele verbetering zijn.

**Comment by SofieVG** [comment]
Mijn idee was inderdaad ook dat ipv 1 goal (zoals momenteel geimplementeerd) een lijst van goals zou gebruikt worden en zodra een bepaalde goal bereikt is (of onbereikbaar blijkt) Kate het pad zoekt naar de volgende goal.
Ik denk dat hiervoor twee opties zijn:
De eenvoudigste is gewoon om een vast aantal punten toe te voegen, zodanig dat ze als ze naar al die punten gaat ze heel de kaart wel ongeveer in beeld zou brengen (in een soort rooster-vorm bv om de meter een punt ofzo).
De andere (en wss betere) optie is om telkens een goal bereikt is te kijken waar er nog weinig informatie over is en dan daarnaar toe te bewegen. Ik denk dat dit verder wordt uitgewerkt in hoofdstuk 17 van het boek.

**Comment by ndsmyter** [comment]
My vote: tweede optie
Reason: hoe meer informatie je weet hoe beter. Kate zal dan waarschijnlijk wel eventjes moeten stoppen en wat dingen berekenen van zodra een punt bereikt is, maar de gevonden tussentijdse informatie kan altijd handig zijn.

**Comment by rcannood** [comment]
Zou ik rechtstreeks hier op kunnen beantwoorden? _test_ (PS: Het gààt om te antwoorden via mail maar tis niet bijzonder praktisch :P)

Godja ^^ Optie één is wel eenvoudiger te implementeren. Kate kan nu ook al toch wel 't een en het ander verkennen (als er geen ruis is), ookal gaat het niet noodzakelijk alles gaan verkennen. Dus dit zou ik niet echt een hoge prioriteit geven.

Otoh ligt de hoogste prioriteit bij Stef, Sander en mij, aangezien we die 2 methodes nog moeten implementeren en dan de fysieke Kate eens moeten uit proberen ^^ Dusja ^^

**Comment by SofieVG** [comment]
De lijst van goals is al een tijdje geïmplementeerd, en vandaag is dan beslist dat we het enkel bij een vaste structuur gaan houden (bij voorkeur in spiraalvorm) en er niet meer gewerkt zou worden aan een intelligente zoekstrategie wegens tijdsgebrek :)
