### ISSUE TITLE
Log vanuit brains

### ISSUE THREAD

**Issue by SofieVG** [ndsmyter/Robotica#5]
Nu is dat enkel mogelijk vanuit emulator

**Comment by ndsmyter** [comment]
Je kan toch wel loggen vanuit Brains ? Ik doe het zelf in de constructor van Brains. Je moet gewoon emulator.log(String message); aanroepen waar je dit wil. Maar ik zal ook nog een methode log(String message) toevoegen in Brains, zodanig dat je onmiddellijk op Brains kan aanroepen. Want dit is waarschijnlijk wat je bedoelde, alhoewel dit niet onmiddellijk duidelijk was uit uw beschrijving.

``` java
public Brains() {
    ...
    log("==========================================");
    log("Initiating application");
}
public void log(String message) {
    emulator.log(message);
}
```

tl;dr: Overal waar je emulator of brains hebt kan je loggen door .log(String message) op te roepen
