### ISSUE TITLE
Goal reached?

### ISSUE THREAD

**Issue by SofieVG** [ndsmyter/Robotica#6]
Bij het detecteren of de robot de goal bereikt heeft gaat het soms fout en rijdt hij er voorbij omdat hij in de vakjes er net naast gepasseerd is. Dit zou mss kunnen opgelost worden door te kijken of het vakje waarin de robot zich bevindt en het "goal" vakje niet te vergelijken om te zien of ze gelijk zijn, maar door te zeggen dat de afstand ertussen kleiner moet zijn dan een bepaalde threshold ofzo

**Comment by ndsmyter** [comment]
Als ik het goed begrijp zou het iets moeten zijn zoals goalReached uit de Utils die ik zonet heb toegevoegd.

(issue is gesloten, als het niet juist is moet je maar opnieuw openen hé ;-) )
