### ISSUE TITLE
Afronding

### ISSUE THREAD

**Issue by SofieVG** [ndsmyter/Robotica#7]
Momenteel wordt afgerond naar de linkeronderhoek van het vakje.
Dat is niet zo logisch, middelpunt zou logischer zijn.
Dit is in pointToGrid al voorzien (met code in commentaar), maar als we hiermee zouden werken zou het wel superhandig zijn moest dit in de view ook zo getoond kunnen worden, want anders wordt alles wel heel verwarrend. 
Is wss niet zo veel werk om aan te passen, maar het is nu al wat te laat om het zelf nog te doen.. Het rechthoekje zou dus ipv op het gegeven punt (x,y) te starten moeten starten op (x - Config.GRID_SIZE/2, y - Config.GRID_SIZE/2)  (wat wss dan nog geschaald moet worden en dus toch nog beetje gepruts zal zijn..)

**Comment by ndsmyter** [comment]
Ik ben niet helemaal mee waar je dit zou willen. Ik heb al op sommige plaatsen in commentaar gezet wat ik vermoed  dat er zou moeten komen. Maar misschien moet je er toch zelf eens naar kijken, of me een iets betere uitleg geven wat ik nu juist moet doen. Want ik snap er nu niet zo veel van :P

Ik snapte ook niet echt hoe uw code juist werkte in die pointToGrid.
Je had:
p.x = p.x - (p.x % Config.GRID_SIZE + Config.GRID_SIZE) % Config.GRID_SIZE;
en ik heb het veranderd naar:
p.x = p.x - (p.x % Config.GRID_CELL_SIZE);
Wat het eigenlijk origineel was toen ik het gisteren heb gecommit, maar ik ben niet zeker waarom je dit eigenlijk aangepast hebt, aangezien het nu toch exact hetzelfde doet ?

**Comment by SofieVG** [comment]
Nee, bij negatieve getallen rond het dan fout af :) met wat ik geschreven
heb zou het wel goed moeten gaan.
Zal dan vanavond eens kijken wat je in GUI in commentaar gezet hebt en of
dat was wat ik bedoelde ^^

**Comment by ndsmyter** [comment]
Oké, ik heb na wat testen in Java ook gemerkt dat het inderdaad fout gaat met negatieve getallen. Heb het nu terug aangepast, en dan ook eens de nodige aanpassingen gedaan in MapPanel en ik denk dat het nu werkt zoals je zou willen.

Je moet maar eens testen en me anders laten weten, of dit issue terug opnieuw openen ;-)
